# Parameters for panda_softhand_safety
# Remember that there might be other important constants that can only be changed from the src code.

panda_softhand_safety:
  # Name of the moveit group
  group_name: panda_arm
  # Collision distance threshold
  collision_threshold: 0.025
  # Name of the root
  root_name: panda_link0
  # Name of the tip
  tip_name: panda_link7
  # Joint position limit violation threshold
  joint_pos_thresh: 0.1
  # Joint velocity limit violation threshold
  joint_vel_thresh: 0.01
  # Joint acceleration limit violation threshold
  joint_acc_thresh: 0.001
  # Acceleration limit for the joints (same for all) (TODO : get the correct acceleration limits from Franka Documentation)
  acceleration_limit: 0.20